repos:
  - repo: local
    hooks:
      - id: maven-format
        name: Maven Format
        entry:  sh -c "mvn spotless:check"
        language: system
        types: [java]
        files: \.java$

      - id: maven-checkstyle
        name: Maven Checkstyle
        entry: sh -c "mvn checkstyle:check"
        language: system
        types: [java]
        files: \.java$
